### ISSUE TITLE
FileNotFoundError in Working_with_kitti_dataset tutorial

### ISSUE THREAD

**Issue by RonaldEnsing** [virtual-vehicle/pointcloudset#8]
I am writing this issue as a JOSS reviewer. See more info here: https://github.com/openjournals/joss-reviews/issues/3471.

The 'Working_with_kitti_dataset' gives the following error:
`FileNotFoundError: [Errno 2] No such file or directory: '/pointcloudset/tutorial_notebooks/kitti_2011_09_26_drive_0002_synced.bag'`

I am using the pointcloudset docker container. Since the python code downloads the data, I'd expect this to work 'out-of-the-box', without the need to configure the paths manually. The bag file seems to be missing entirely.

**Comment by tgoelles** [comment]
Hi. Thanks for reviewing our package!

Yes we didn't want to include the bag file in the repo as it is too large and to avoid any license issues. Also KITTI does not provide bag files directly. In order to get the data you need to run cell 3 in [Working_with_kitti_dataset.ipynb](https://github.com/virtual-vehicle/pointcloudset/blob/master/doc/sphinx/source/tutorial_notebooks/Working_with_kitti_dataset.ipynb)

With  uncommented `docker run ...` line like this:

```
!wget https://s3.eu-central-1.amazonaws.com/avg-kitti/raw_data/2011_09_26_drive_0002/2011_09_26_drive_0002_sync.zip
!wget https://s3.eu-central-1.amazonaws.com/avg-kitti/raw_data/2011_09_26_calib.zip
!unzip 2011_09_26_drive_0002_sync.zip
!unzip 2011_09_26_calib.zip
!docker run -v `pwd`:/data -it yoyo860224/kitti2bag -t 2011_09_26 -r 0002 raw_synced
```

This will download the data and convert it to a bagfile with the help of yoyo860224/kitti2bag.
The other notebooks should work out of the box, as they are also included in the automatic tests.

(@tobiashammer)

**Comment by RonaldEnsing** [comment]
Ah, I see. What is the reason for commenting the `kitti2bag` docker command?

I am running the notebook in a docker container. So the `docker run ...` would become a nested docker command.

Would it be an idea to make `kitti2bag` available in the pointcloudset docker image so that the tutorials can be run directly from the pointcloudset containers?

**Comment by tgoelles** [comment]
Yes thats the reason it is commented, to avoid issues with nested docker commands. So you could run the whole command of cell 3 outside of docker to get the bag file.

kitti2bag is quite hard to install and we want to avoid the additional complexity. We included the notebook just to show that pointcloudset also works with KITTI if needed.

**Comment by RonaldEnsing** [comment]
OK, clear. Maybe it would be a good idea to clarify this in the notebook?

**Comment by tobiashammer** [comment]
Hi, yes I will update the notebook.
